main/urls.py
import imp
from django.urls import path
from . import views


app_name = 'main'

urlpatterns =[

    path('', views.IndexView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('portfolio/', views.PortfolioView.as_view(), name='portfolio'),
    path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name='portfolio_detail'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name='blog_detail'),

]

resume/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from tabnanny import verbose
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


# Create your models here.


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'

    name = models.CharField(max_length=20, blank=True, null= True)
    score = models.IntegerField(default=80, blank=True, null= True)
    image = models.FileField(blank=True, null= True, upload_to='skills')
    is_key_skill = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'

    user = models.OneToOneField (User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null= True, upload_to= 'avatar')
    title = models.CharField (max_length=200, blank=True, null=True)
    bio = models.TextField (blank=True, null=True)
    skills = models.ManyToManyField (Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to='cv')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'



class ContactProfile(models.Model):

    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ['timestamp']

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField (max_length=200, blank=False, null=False, verbose_name='Name')
    email = models.EmailField(blank=False, null=False, verbose_name='Email')
    message = models.TextField (blank=False, null=False, verbose_name='Message')

    def __str__(self):
        return f'{self.name}'


class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonials'
        ordering = ['name']

    thumbnail = models.ImageField(blank=True, null= True, upload_to= 'thumbnail')
    name = models.CharField (max_length=200, blank=True, null=True)
    role = models.CharField (max_length=200, blank=True, null=True)
    quote = models.CharField (max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Medias'
        verbose_name = 'Media'
        ordering = ['name']

    image = models.ImageField(blank=True, null= True, upload_to= 'media')
    url = models.URLField (blank=True, null=True, verbose_name='url')
    name = models.CharField(max_length=200 ,blank=True, null=True, verbose_name='name')
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'


class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Porfolios'
        verbose_name = 'Portfolio'
        ordering = ['name']

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField (max_length=200, blank=True, null=True, verbose_name='name')
    description = models.CharField(max_length=500 ,blank=True, null=True, verbose_name='description')
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to= 'media')
    url = models.URLField (blank=True, null=True, verbose_name='url')
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/portfolio/{self.slug}'


class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blogs'
        verbose_name = 'Blog'
        ordering = ['datetime']

    datetime = models.DateTimeField(auto_now_add=True)
    author = models.CharField (max_length=200, blank=True, null=True, verbose_name='author')
    name = models.CharField (max_length=200, blank=True, null=True, verbose_name='name')
    description = models.CharField(max_length=500 ,blank=True, null=True, verbose_name='description')
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to= 'blog')
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/blog/{self.slug}'


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField (max_length=200, blank=True, null=True, verbose_name='name')
    title = models.CharField(max_length=500 ,blank=True, null=True, verbose_name='title')
    description = models.CharField(max_length=500 ,blank=True, null=True, verbose_name='description')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

main/forms.py
from django import forms
from . models import ContactProfile

class ContactForm(forms.ModelForm):

    name = forms.CharField(max_length=100, required=True,
        widget=forms.TextInput(attrs={
            'placeholder': '*Full Name...',
            # 'class': 'form-control'
        }))
    email = forms.EmailField(max_length=254, required=True,
        widget=forms.TextInput(attrs={
            'placeholder': '*Email Address...',
            # 'class': 'form-control'
        }))
    message = forms.CharField(max_length=1000, required=True,
        widget=forms.TextInput(attrs={
            'placeholder': '*Your Message Here...',
            'rows': 6
            # 'class': 'form-control'
        }))

    
    class Meta:
        model = ContactProfile
        fields = ('name', 'email', 'message')

main/views.py
from re import template
from django.shortcuts import render
from django.contrib import messages
from . models import *
from django.views import generic
from . forms import ContactForm

# Create your views here.


class IndexView(generic.TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        certificates = Certificate.objects.filter(is_active=True)
        blogs = Blog.objects.filter(is_active=True)
        portfolios = Portfolio.objects.filter(is_active=True)

        context['testimonials'] = testimonials
        context['certificates'] = certificates
        context['blogs'] = blogs
        context['portfolios'] = portfolios

        return context


class ContactView(generic.FormView):
    template_name = 'main/contact.html'
    form_class = ContactForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Thank you. We we will be in touch soon.')
        return super().form_invalid(form)


class PortfolioView(generic.ListView):
    model = Portfolio
    context_object_name = 'portfolio'
    template_name = 'main/portfolio.html'
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    context_object_name = 'portfolio_detail'
    template_name = 'main/portfolio-detail.html'


class BlogView(generic.ListView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'main/blog.html'

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
    model = Blog
    context_object_name = 'blog_detail'
    template_name = 'main/blog-detail.html'

main/templates/main/partials/footer.html
{% load static %}

<footer>
    <div class="footerCol">
      <div class="container">
        <ul class="socialCol">
          <li><a href="https://www.facebook.com/shuvamsinghhamal/" target="_blank"><img src="{% static 'images/fb.svg' %}" alt="..."></a></li>
          <li><a href="https://www.instagram.com/shuvamsinghhamal/" target="_blank"><img src="{% static 'images/insta.svg' %}" alt="..."></a></li>
          {% comment %} <li><a href="javascript:void(0)" target="_blank"><img src="{% static 'images/twitter.svg' %}" alt="..."></a></li> {% endcomment %}
          <li><a href="https://github.com/Shuvam77" target="_blank"><img src="{% static 'images/github.svg' %}" alt="..."></a></li>
          <li><a href="https://www.linkedin.com/in/shuvam77/" target="_blank"><img src="{% static 'images/linkedin.svg' %}" alt="..."></a></li>
        </ul>
        <div class="copyrightCol">
          <p>Copyright ©2021 All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">James Granger Design</a></p>
        </div>
      </div>
    </div>
  </footer>

main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
            <script>alert("{{ message }}")</script>
        {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/partials/nav.html
{% load static %}

<header>
    <div class="headerCol">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-auto col-3">
            <div class="logoCol"><a href="/"><img src="{% static 'images/icon1.png' %}" width="10%" height="10%" alt="..."></a></div>
          </div>
          <div class="col col-9">
            <div class="d-md-none">
              <button class="navToggle">
                <span class="navToggle__text">Toggle Menu</span>
              </button>
            </div>
            <div class="navCollapseCol">
              <div class="navCol">
                <ul>
                  <li><a href="/">Home</a></li>
                  <li><a href="{% url 'main:portfolio' %}">Portfolio</a></li>
                  <li><a href="{% url 'main:blog' %}">Blog</a></li>
                  <li><a href="{% url 'main:contact' %}">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>